# Quantum Random Walk Search
Source: 
* https://arxiv.org/pdf/quant-ph/0210064.pdf
* https://digitalcommons.calpoly.edu/cgi/viewcontent.cgi?article=1202&context=physsp


## Operator + State Definitions

In [1]:
import numpy as np

In [2]:
n = 2

psi_c = 1/2**0.5 * np.array([[1],
                            [1]]) # equal superposition

G = 2*np.outer(psi_c, psi_c.T) - np.eye(n)

In [3]:
G = np.round(G)

In [4]:
print(G)

[[-0.  1.]
 [ 1. -0.]]


In [5]:
S = np.kron(np.array([[1,0],[0,0]]), np.array([[0,1,0,0],[1,0,0,0],[0,0,0,1],[0,0,1,0]])) \
    + np.kron(np.array([[0,0],[0,1]]), np.array([[0,0,1,0], [0,0,0,1], [1,0,0,0], [0,1,0,0]]))

print(S)

[[0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 1 0 0]]


In [6]:
U = S @ (np.kron(G, np.eye(2**n)))

In [7]:
print(U)

[[0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]]


In [8]:
## instantiate target state

x_target = np.array([[0],
                    [1],
                    [0],
                    [0]]) ## |x_target> = |01>

# x_target = np.array([[1],[0],[0],[0]])
# x_target = np.array([[0], [0], [0], [1]])

In [9]:
C = - np.eye(n)

In [10]:
C_prime = np.kron(G, np.eye(2**n)) + np.kron((C - G), np.outer(x_target, x_target.T) )

## Revised C_prime operator: 
"the oracle
acts instead by applying a marking coin, C1, to the marked node and a different coin, C, to the unmarked nodes"

Accordingly, instead of combining (C-G) with |x_target> <x_target|, it seems to make more sense to combine just (C) with |x_target> <x_target|. Whether the paper's formula is thereby just a typo, the world will never know...

In [11]:
## replace (C-G) with just C
C_prime_revised = np.kron(G, np.eye(2**n)) + np.kron(C, np.outer(x_target, x_target.T) )

In [12]:
print(C_prime)

[[-0. -0. -0. -0.  1.  0.  0.  0.]
 [-0. -1. -0. -0.  0.  0.  0.  0.]
 [-0. -0. -0. -0.  0.  0.  1.  0.]
 [-0. -0. -0. -0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0. -0. -0. -0. -0.]
 [ 0.  0.  0.  0. -0. -1. -0. -0.]
 [ 0.  0.  1.  0. -0. -0. -0. -0.]
 [ 0.  0.  0.  1. -0. -0. -0. -0.]]


In [13]:
print(C_prime_revised)

[[-0. -0. -0. -0.  1.  0.  0.  0.]
 [-0. -1. -0. -0.  0.  1.  0.  0.]
 [-0. -0. -0. -0.  0.  0.  1.  0.]
 [-0. -0. -0. -0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0. -0. -0. -0. -0.]
 [ 0.  1.  0.  0. -0. -1. -0. -0.]
 [ 0.  0.  1.  0. -0. -0. -0. -0.]
 [ 0.  0.  0.  1. -0. -0. -0. -0.]]


In [14]:
U_prime = S @ C_prime

In [15]:
U_prime_revised = S @ C_prime_revised

In [16]:
print(U_prime)

[[ 0. -1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. -1.  0.  0.]]


In [17]:
print(U_prime_revised)

[[ 0. -1.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0. -1.  0.  0.]]


## Search Evaluation
Note: optimal number of evolutions is $\lfloor \frac{\pi}{2} \sqrt{2^n} \rfloor = 3$

(See page 3 of https://arxiv.org/pdf/quant-ph/0210064.pdf)

### Using original U_prime evolution operator

In [18]:
## initialization
psi_0 = np.kron(psi_c, 1/2*(np.array([[1],[1],[1],[1]])))

In [19]:
print(psi_0)

[[0.35355339]
 [0.35355339]
 [0.35355339]
 [0.35355339]
 [0.35355339]
 [0.35355339]
 [0.35355339]
 [0.35355339]]


In [20]:
## first evolution
psi_1 = U_prime @ psi_0

In [21]:
print(psi_1)

[[-0.35355339]
 [ 0.35355339]
 [ 0.35355339]
 [ 0.35355339]
 [ 0.35355339]
 [ 0.35355339]
 [ 0.35355339]
 [-0.35355339]]


In [22]:
## second evolution
psi_2 = U_prime @ psi_1

In [23]:
print(psi_2)

[[-0.35355339]
 [ 0.35355339]
 [-0.35355339]
 [ 0.35355339]
 [ 0.35355339]
 [ 0.35355339]
 [-0.35355339]
 [-0.35355339]]


In [24]:
## third evolution
psi_3 = U_prime @ psi_2

In [25]:
print(psi_3)

[[-0.35355339]
 [ 0.35355339]
 [-0.35355339]
 [-0.35355339]
 [-0.35355339]
 [ 0.35355339]
 [-0.35355339]
 [-0.35355339]]


In [26]:
## fourth evolution
psi_4 = U_prime @ psi_3

In [27]:
print(psi_4) # note: this seems to be going in circles

[[-0.35355339]
 [-0.35355339]
 [-0.35355339]
 [-0.35355339]
 [-0.35355339]
 [-0.35355339]
 [-0.35355339]
 [-0.35355339]]


In [28]:
## fifth evolution
psi_5 = U_prime @ psi_4

In [29]:
print(psi_5) # note: the probability of measuring the target state has not improved since the initial state

[[ 0.35355339]
 [-0.35355339]
 [-0.35355339]
 [-0.35355339]
 [-0.35355339]
 [-0.35355339]
 [-0.35355339]
 [ 0.35355339]]


#### Result: 
The repeated evolutions only flip the phases of the superimposed states, and the coefficient of the target state remains the same as the non-target states

### Using U_prime_revised evolution operator
Note: In definition of C_prime_revised, (C-G) is replaced with C

In [30]:
## initialization
psi_0 = np.kron(psi_c, 1/2*(np.array([[1],[1],[1],[1]])))

In [31]:
print(psi_0)

[[0.35355339]
 [0.35355339]
 [0.35355339]
 [0.35355339]
 [0.35355339]
 [0.35355339]
 [0.35355339]
 [0.35355339]]


In [32]:
## first evolution
psi_1 = U_prime_revised @ psi_0

In [33]:
print(psi_1)

[[0.        ]
 [0.35355339]
 [0.35355339]
 [0.35355339]
 [0.35355339]
 [0.35355339]
 [0.35355339]
 [0.        ]]


In [34]:
## second evolution
psi_2 = U_prime_revised @ psi_1

In [35]:
print(psi_2) # note: here, the probability of measuring the target state is improved to 50% (accounting for renormalization)
# state: |0>|01> + |0>|11> + |1>|00> + |1>|01>

[[0.        ]
 [0.35355339]
 [0.        ]
 [0.35355339]
 [0.35355339]
 [0.35355339]
 [0.        ]
 [0.        ]]


In [36]:
## third evolution
psi_3 = U_prime_revised @ psi_2

In [37]:
print(psi_3) # note: here, the probability of measuring the target state is greatly improved to 100% (accounting for renormalization)
# state: |0>|01> + |1>|01>

[[0.        ]
 [0.35355339]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.35355339]
 [0.        ]
 [0.        ]]


In [38]:
## fourth evolution
psi_4 = U_prime_revised @ psi_3

In [39]:
print(psi_4) # note: after this point, the evolutions no longer benefit the search

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]


In [40]:
## fifth evolution
psi_5 = U_prime_revised @ psi_4

In [41]:
print(psi_5)

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]


#### Result:
The repeated evolutions eliminate the amplitudes of non-target states, thereby increasing the amplitude of the desired target state, until there is a 50% chance of measuring the target state after the third evolution. 

However, evolutions beyond the optimal number will have a negative effect on the search result